# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stuff',
            field=models.TextField(default='tavo mama'),
        ),
    ]
